services:
  discovery-services:
    build: ./Discovry-service
    container_name: discovery-services
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4
  config-services:
    build: ./Config-Service
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-services:8761/eureka
    depends_on:
      discovery-services:
        condition: service_healthy



  achteur-service:
    build: ./Achteur
    container_name: achteur-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8081/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-services:8761/eureka
      - CONFIG-SERVICE_URL=http://config-services:9999
    depends_on:
      config-services:
        condition: service_healthy

  produit-service:
    build: ./Produit
    container_name: produit-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-services:8761/eureka
      - CONFIG-SERVICE_URL=http://config-services:9999
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8082/actuator/health" ]
    depends_on:
      achteur-service:
        condition: service_healthy

  vente-service:
      build: ./Vente
      container_name: vente-service
      ports:
        - '8083:8083'
      expose:
        - '8083'
      environment:
        - DISCOVERY_SERVICE_URL=http://discovery-services:8761/eureka
        - CONFIG-SERVICE_URL=http://config-services:9999
      healthcheck:
        test: [ "CMD","curl","-f","http://localhost:8083/actuator/health" ]
      depends_on:
        produit-service:
          condition: service_healthy


  gatway-service:
        build: ./GatWay-service
        container_name: gatway-service
        ports:
          - '8888:8888'
        expose:
          - '8888'
        environment:
          - DISCOVERY_SERVICE_URL=http://discovery-services:8761/eureka
          - CONFIG-SERVICE_URL =http://config-services:9999
        depends_on:
          vente-service:
            condition: service_healthy
